package backend.model;

public enum CycleStatus {
    PREDICTED,
    WAITING_FOR_START_CONFIRMATION,
    ACTIVE,
    WAITING_FOR_END_CONFIRMATION,
    COMPLETED,
    START_CONFIRMATION_EXPIRED,
    END_CONFIRMATION_EXPIRED
}
