spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cyclescope
spring.datasource.username=postgres
spring.datasource.password=strawberry321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true